name: Mongodb deploy
on: [push]
permissions: write-all

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3

    - name: 'Liquibase Status'
      uses: liquibase-github-actions/status@v4.29.1
      with:
        defaultsFile: ./liquibase/changelog/liquibase.atlas.properties




      
