name: Mongodb deploy
on: [push]
permissions: write-all

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v4

    - name: 'Liquibase Status'
      uses: liquibase-github-actions/status@v4.29.1
      with:
        searchPath: "./liquibase/changelog"
        url: "mongodb://localhost:27017/liquibase_learn"
        changelogFile: "changelog.xml"
        classpath: "./liquibase/changelog/bson-5.1.2.jar:./liquibase/changelog/liquibase-mongodb-4.28.0.jar:./liquibase/changelog/mongodb-driver-core-5.1.2.jar:./liquibase/changelog/mongodb-driver-sync-5.1.2.jar"     
